name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: kacestudio/laravel-deploy-runner:latest
    env:
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      -
        run: git config --global --add safe.directory /__w/nginx-demo/nginx-demo
      - 
        name: Run Deployment
        run: kamal envify; kamal deploy